name: Demo Test

on:
  - push
  - pull_request

jobs:
  test-theme-default:
    name: Test default with node 18
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Default theme build
        run: |
          pnpm --filter vitepress-theme-default build

      - name: Demo build test
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pnpm --filter theme-demo demo:default-build

  test-theme-hope:
    name: Test hope with node 18
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Hope theme build
        run: |
          pnpm --filter vitepress-theme-hope build

      - name: Demo build test
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pnpm --filter theme-demo demo:build
